language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - cd ./example
  - yarn
script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: example/build
  on:
    branch: master
